name: Build phar

on:
  push:
    branches:
      - master
      - 6.x
      - add_docker_image
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-phar:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
        env:
          fail-fast: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for composer to automatically detect root package version

      - name: Upload docker image
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          bin/ci/build-docker.php
